# Generated by Django 4.1.5 on 2023-01-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('cast', models.CharField(max_length=200)),
                ('synopsis', models.CharField(max_length=500)),
                ('genre', models.CharField(choices=[('Matutino', 'Morning'), ('Vespertino', 'Afternoon'), ('Noturno', 'Night'), ('Não informado', 'Default')], default='Não informado', max_length=50, null=True)),
                ('release_year', models.IntegerField()),
                ('age_rating', models.CharField(choices=[('Matutino', 'Morning'), ('Vespertino', 'Afternoon'), ('Noturno', 'Night'), ('Não informado', 'Default')], default='Não informado', max_length=50, null=True)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
