# Generated by Django 4.1.5 on 2023-01-16 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doramas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorama',
            name='poster',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dorama',
            name='trailer',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
