# Generated by Django 4.1.5 on 2023-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doramas', '0002_dorama_poster_dorama_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorama',
            name='poster',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dorama',
            name='trailer',
            field=models.URLField(max_length=300),
        ),
    ]
