# Generated by Django 4.1.5 on 2023-01-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doramas', '0003_alter_dorama_poster_alter_dorama_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorama',
            name='synopsis',
            field=models.CharField(max_length=1500),
        ),
    ]
