# Generated by Django 4.1.5 on 2023-01-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doramas', '0004_alter_dorama_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorama',
            name='age_rating',
            field=models.CharField(choices=[('Livre', 'Livre'), ('10', 'Dez'), ('12', 'Doze'), ('14', 'Quatorze'), ('16', 'Dezesseis'), ('18', 'Dezoito'), ('Não informado', 'Default')], default='Não informado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dorama',
            name='genre',
            field=models.CharField(choices=[('romance', 'Morning'), ('escolar', 'Afternoon'), ('comédia', 'Night'), ('policial', 'Policial'), ('drama médico', 'Medicina'), ('ficção científica', 'Ficçao'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('outro', 'Outro'), ('Não informado', 'Default')], default='Não informado', max_length=50, null=True),
        ),
    ]
