# Generated by Django 4.1.5 on 2023-01-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doramas', '0005_alter_dorama_age_rating_alter_dorama_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorama',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
